version: "3.9"
services:
    postgres:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome1}
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      restart: unless-stopped

    pgadmin:
      container_name: pgadmin
      image: "dpage/pgadmin4"
      restart: on-failure
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "8080:80"
      volumes:
        - pgadmin-data:/var/lib/pgadmin

    web:
          image: fastapi
          container_name: fastapi
          build: .
          ports:
            - 8000:8000
          command: uvicorn main:app --host 0.0.0.0 --port 8000

          depends_on:
            - postgres
volumes:
    postgres:
    pgadmin-data: